### ISSUE TITLE
Can't run on Java8

### ISSUE THREAD

**Issue by freewind** [greenlaw110/Rythm#215]
Java8:

    java version "1.8.0_05"
    Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

Error message:

```
Caused by: java.lang.RuntimeException: org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at com.greenlaw110.rythm.internal.compiler.TemplateCompiler$1.findType(TemplateCompiler.java:232)
	at com.greenlaw110.rythm.internal.compiler.TemplateCompiler$1.findType(TemplateCompiler.java:177)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:113)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1335)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromVariantTypeSignature(LookupEnvironment.java:1391)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeArgumentsFromSignature(LookupEnvironment.java:1172)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1340)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethod(BinaryTypeBinding.java:550)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createMethods(BinaryTypeBinding.java:630)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:365)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:688)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:667)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:296)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:118)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:49)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:122)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:168)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getPackage(Scope.java:2379)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedQualifiedTypeReference.internalResolveLeafType(ParameterizedQualifiedTypeReference.java:138)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedQualifiedTypeReference.internalResolveType(ParameterizedQualifiedTypeReference.java:132)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedQualifiedTypeReference.resolveType(ParameterizedQualifiedTypeReference.java:351)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:1538)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods(SourceTypeBinding.java:1175)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:678)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:469)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:756)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:468)
	at com.greenlaw110.rythm.internal.compiler.TemplateCompiler.compile(TemplateCompiler.java:333)
	at com.greenlaw110.rythm.internal.compiler.TemplateClass.compile(TemplateClass.java:641)
	at com.greenlaw110.rythm.internal.compiler.TemplateClassLoader.loadTemplateClass(TemplateClassLoader.java:306)
	at com.greenlaw110.rythm.internal.compiler.TemplateClassLoader.loadClass(TemplateClassLoader.java:251)
	at com.greenlaw110.rythm.internal.compiler.TemplateClass.getJavaClass(TemplateClass.java:348)
	at com.greenlaw110.rythm.internal.compiler.TemplateClass.templateInstance_(TemplateClass.java:365)
	... 60 more
Caused by: org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:372)
	at com.greenlaw110.rythm.internal.compiler.TemplateCompiler$1.findStandType(TemplateCompiler.java:197)
	at com.greenlaw110.rythm.internal.compiler.TemplateCompiler$1.findType(TemplateCompiler.java:211)
	... 94 more
```

**Comment by alfishe** [comment]
Issue is still active for *nix and Mac OS X. The reason is - unrecognizable path format used in unit test template file.
Should be like @extends(./shared/user.txt) instead of @extends(shared\user.txt)
Seems was tested under Windows only. I'll prepare pull request for that

**Comment by greenlaw110** [comment]
@freewind can you try again on the latest master branch? I am now able to pass unit test on my linux mint OS

**Comment by freewind** [comment]
```
➜  Rythm git:(master) java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
➜  Rythm git:(master) mvn clean test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Rythm Template Engine 1.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ rythm-engine ---
[INFO] Deleting /Users/twer/workspace/Rythm/target
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ rythm-engine ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rythm-engine ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ rythm-engine ---
[INFO] Compiling 201 source files to /Users/twer/workspace/Rythm/target/classes
[WARNING] /Users/twer/workspace/Rythm/src/main/java/org/rythmengine/sandbox/RythmSecurityManager.java:[29,24] SecurityConstants is internal proprietary API and may be removed in a future release
[WARNING] /Users/twer/workspace/Rythm/src/main/java/org/rythmengine/sandbox/RythmSecurityManager.java:[29,24] SecurityConstants is internal proprietary API and may be removed in a future release
[WARNING] /Users/twer/workspace/Rythm/src/main/java/org/rythmengine/sandbox/RythmSecurityManager.java:[29,24] SecurityConstants is internal proprietary API and may be removed in a future release
[WARNING] /Users/twer/workspace/Rythm/src/main/java/org/rythmengine/sandbox/RythmSecurityManager.java:[323,29] SecurityConstants is internal proprietary API and may be removed in a future release
[WARNING] /Users/twer/workspace/Rythm/src/main/java/org/rythmengine/sandbox/RythmSecurityManager.java:[326,29] SecurityConstants is internal proprietary API and may be removed in a future release
[WARNING] /Users/twer/workspace/Rythm/src/main/java/org/rythmengine/sandbox/RythmSecurityManager.java:[329,29] SecurityConstants is internal proprietary API and may be removed in a future release
[WARNING] /Users/twer/workspace/Rythm/src/main/java/org/rythmengine/sandbox/RythmSecurityManager.java:[332,29] SecurityConstants is internal proprietary API and may be removed in a future release
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rythm-engine ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 80 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ rythm-engine ---
[INFO] Compiling 48 source files to /Users/twer/workspace/Rythm/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ rythm-engine ---
[INFO] Surefire report directory: /Users/twer/workspace/Rythm/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.rythmengine.advanced.JSONParameterTest
log4j:WARN No appenders could be found for logger (org.rythmengine.RythmEngine).
log4j:WARN Please initialize the log4j system properly.
@args List<org.rythmengine.advanced.JSONParameterTest.User> users
<ul>@for(users){
@_.name: @_.age
}</ul>
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.415 sec
Running org.rythmengine.advanced.NaturalTemplateTest
Tests run: 4, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.45 sec <<< FAILURE!
testBasicDirectives(org.rythmengine.advanced.NaturalTemplateTest)  Time elapsed: 0.185 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: <!-- @for (1..5) {-->@(_)@_sep<!-- } -->

Relevant template source lines:
-------------------------------------------------
>> 1: <!-- @for (1..5) {-->@(_)@_sep<!-- } -->


Relevant Java source lines:
-------------------------------------------------
   85:
   86:
   87: 	@Override public org.rythmengine.utils.TextBuilder build(){
   88: 		buffer().ensureCapacity(40);
   89: {
>> 90: __Itr __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..5")); //line: 1
   91: int _size = __v0.size(); //line: 1
   92: if (_size > 0) { //line: 1
   93: int _index = 0; //line: 1
   94: for(java.lang.Object _ : __v0) { //line: 1
   95: _index++; //line: 1
   96: boolean _isOdd = _index % 2 == 1; //line: 1



testFeatureDisabled(org.rythmengine.advanced.NaturalTemplateTest)  Time elapsed: 0.132 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: <!-- @for (1..5) {-->@(_)@_sep<!-- } -->

Relevant template source lines:
-------------------------------------------------
>> 1: <!-- @for (1..5) {-->@(_)@_sep<!-- } -->


Relevant Java source lines:
-------------------------------------------------
   86:
   87: 	@Override public org.rythmengine.utils.TextBuilder build(){
   88: 		buffer().ensureCapacity(40);
   89: p("<!-- "); //line: 1
   90: {
>> 91: __Itr __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..5")); //line: 1
   92: int _size = __v0.size(); //line: 1
   93: if (_size > 0) { //line: 1
   94: int _index = 0; //line: 1
   95: for(java.lang.Object _ : __v0) { //line: 1
   96: _index++; //line: 1
   97: boolean _isOdd = _index % 2 == 1; //line: 1



Running org.rythmengine.advanced.SmartEscapeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 sec
Running org.rythmengine.advanced.TransformerTest
json
xml
javascript
html
csv
raw
113,432.33
000.03
04/04/2015 11:39
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.844 sec
Running org.rythmengine.advanced.TypeInferenceTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.119 sec
Running org.rythmengine.cache.SimpleCacheServiceTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.447 sec
Running org.rythmengine.essential.ArgsParserTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.299 sec
Running org.rythmengine.essential.AssignParserTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.156 sec
Running org.rythmengine.essential.BraceParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec
Running org.rythmengine.essential.CacheParserTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.663 sec
Running org.rythmengine.essential.CommentTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.205 sec
Running org.rythmengine.essential.CompactModeTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.177 sec
Running org.rythmengine.essential.CompactParserTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.164 sec
Running org.rythmengine.essential.DebugParserTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.079 sec
Running org.rythmengine.essential.EscapeParserTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.197 sec
Running org.rythmengine.essential.ExpressionTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.378 sec
Running org.rythmengine.essential.FinallyParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
Running org.rythmengine.essential.ForParserTest
Tests run: 31, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 1.251 sec <<< FAILURE!
testRangeExpression(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.025 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for (int i : 1 .. 5) {@i}

Relevant template source lines:
-------------------------------------------------
>> 1: @for (int i : 1 .. 5) {@i}


Relevant Java source lines:
-------------------------------------------------
   66:
   67:
   68: 	@Override public org.rythmengine.utils.TextBuilder build(){
   69: 		buffer().ensureCapacity(26);
   70: {
>> 71: __Itr<Integer> __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1 .. 5")); //line: 1
   72: int i_size = __v0.size(); //line: 1
   73: if (i_size > 0) { //line: 1
   74: int i_index = 0; //line: 1
   75: for(Integer i : __v0) { //line: 1
   76: i_index++; //line: 1
   77: boolean i_isOdd = i_index % 2 == 1; //line: 1



testSimpleStyle(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.079 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for (1 till 5) @_ @

Relevant template source lines:
-------------------------------------------------
>> 1: @for (1 till 5) @_ @


Relevant Java source lines:
-------------------------------------------------
   70:
   71:
   72: 	@Override public org.rythmengine.utils.TextBuilder build(){
   73: 		buffer().ensureCapacity(20);
   74: {
>> 75: __Itr __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1 till 5")); //line: 1
   76: int _size = __v0.size(); //line: 1
   77: if (_size > 0) { //line: 1
   78: int _index = 0; //line: 1
   79: for(java.lang.Object _ : __v0) { //line: 1
   80: _index++; //line: 1
   81: boolean _isOdd = _index % 2 == 1; //line: 1



testLoopVarSize(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.022 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for(1..5){@(_)/@(_size)@_sep}

Relevant template source lines:
-------------------------------------------------
>> 1: @for(1..5){@(_)/@(_size)@_sep}


Relevant Java source lines:
-------------------------------------------------
   69:
   70:
   71: 	@Override public org.rythmengine.utils.TextBuilder build(){
   72: 		buffer().ensureCapacity(30);
   73: {
>> 74: __Itr __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..5")); //line: 1
   75: int _size = __v0.size(); //line: 1
   76: if (_size > 0) { //line: 1
   77: int _index = 0; //line: 1
   78: for(java.lang.Object _ : __v0) { //line: 1
   79: _index++; //line: 1
   80: boolean _isOdd = _index % 2 == 1; //line: 1



testLoopVarParity(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.016 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for(1..5){@(_):@(_parity)@_sep}

Relevant template source lines:
-------------------------------------------------
>> 1: @for(1..5){@(_):@(_parity)@_sep}


Relevant Java source lines:
-------------------------------------------------
   69:
   70:
   71: 	@Override public org.rythmengine.utils.TextBuilder build(){
   72: 		buffer().ensureCapacity(32);
   73: {
>> 74: __Itr __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..5")); //line: 1
   75: int _size = __v0.size(); //line: 1
   76: if (_size > 0) { //line: 1
   77: int _index = 0; //line: 1
   78: for(java.lang.Object _ : __v0) { //line: 1
   79: _index++; //line: 1
   80: boolean _isOdd = _index % 2 == 1; //line: 1



testLoopVarFirstLast(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.021 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for(1..5){@(_):@if(_isFirst){[f]}else if(_isLast){[l]}else{[]}@_sep}

Relevant template source lines:
-------------------------------------------------
>> 1: @for(1..5){@(_):@if(_isFirst){[f]}else if(_isLast){[l]}else{[]}@_sep}


Relevant Java source lines:
-------------------------------------------------
   69:
   70:
   71: 	@Override public org.rythmengine.utils.TextBuilder build(){
   72: 		buffer().ensureCapacity(69);
   73: {
>> 74: __Itr __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..5")); //line: 1
   75: int _size = __v0.size(); //line: 1
   76: if (_size > 0) { //line: 1
   77: int _index = 0; //line: 1
   78: for(java.lang.Object _ : __v0) { //line: 1
   79: _index++; //line: 1
   80: boolean _isOdd = _index % 2 == 1; //line: 1



testBreak(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.023 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for(int i in 1..10){@(i)@if(i > 3){@break}}

Relevant template source lines:
-------------------------------------------------
>> 1: @for(int i in 1..10){@(i)@if(i > 3){@break}}


Relevant Java source lines:
-------------------------------------------------
   65:
   66:
   67: 	@Override public org.rythmengine.utils.TextBuilder build(){
   68: 		buffer().ensureCapacity(44);
   69: {
>> 70: __Itr<Integer> __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..10")); //line: 1
   71: int i_size = __v0.size(); //line: 1
   72: if (i_size > 0) { //line: 1
   73: int i_index = 0; //line: 1
   74: for(Integer i : __v0) { //line: 1
   75: i_index++; //line: 1
   76: boolean i_isOdd = i_index % 2 == 1; //line: 1



testBreakWithIf(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.037 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for(int i in 1..10){@(i) @breakIf(i > 3)}

Relevant template source lines:
-------------------------------------------------
>> 1: @for(int i in 1..10){@(i) @breakIf(i > 3)}


Relevant Java source lines:
-------------------------------------------------
   65:
   66:
   67: 	@Override public org.rythmengine.utils.TextBuilder build(){
   68: 		buffer().ensureCapacity(42);
   69: {
>> 70: __Itr<Integer> __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..10")); //line: 1
   71: int i_size = __v0.size(); //line: 1
   72: if (i_size > 0) { //line: 1
   73: int i_index = 0; //line: 1
   74: for(Integer i : __v0) { //line: 1
   75: i_index++; //line: 1
   76: boolean i_isOdd = i_index % 2 == 1; //line: 1



testContinue(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.02 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for(int i in 1..10){@if((i % 2) == 0){@continueIf}@i}

Relevant template source lines:
-------------------------------------------------
>> 1: @for(int i in 1..10){@if((i % 2) == 0){@continueIf}@i}


Relevant Java source lines:
-------------------------------------------------
   65:
   66:
   67: 	@Override public org.rythmengine.utils.TextBuilder build(){
   68: 		buffer().ensureCapacity(54);
   69: {
>> 70: __Itr<Integer> __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..10")); //line: 1
   71: int i_size = __v0.size(); //line: 1
   72: if (i_size > 0) { //line: 1
   73: int i_index = 0; //line: 1
   74: for(Integer i : __v0) { //line: 1
   75: i_index++; //line: 1
   76: boolean i_isOdd = i_index % 2 == 1; //line: 1



testContinueWithIf(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.019 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for(int i in 1..10){@continueIf(i % 2 == 0) @i}

Relevant template source lines:
-------------------------------------------------
>> 1: @for(int i in 1..10){@continueIf(i % 2 == 0) @i}


Relevant Java source lines:
-------------------------------------------------
   65:
   66:
   67: 	@Override public org.rythmengine.utils.TextBuilder build(){
   68: 		buffer().ensureCapacity(48);
   69: {
>> 70: __Itr<Integer> __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..10")); //line: 1
   71: int i_size = __v0.size(); //line: 1
   72: if (i_size > 0) { //line: 1
   73: int i_index = 0; //line: 1
   74: for(Integer i : __v0) { //line: 1
   75: i_index++; //line: 1
   76: boolean i_isOdd = i_index % 2 == 1; //line: 1



testJoin(org.rythmengine.essential.ForParserTest)  Time elapsed: 0.104 sec  <<< ERROR!
org.rythmengine.exception.CompileException: The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr

Template: @for(1..5).join(){@_}

Relevant template source lines:
-------------------------------------------------
>> 1: @for(1..5).join(){@_}


Relevant Java source lines:
-------------------------------------------------
   69:
   70:
   71: 	@Override public org.rythmengine.utils.TextBuilder build(){
   72: 		buffer().ensureCapacity(21);
   73: {
>> 74: __Itr __v0 = __Itr.valueOf(org.rythmengine.utils.Range.valueOf("1..5")); //line: 1
   75: int _size = __v0.size(); //line: 1
   76: if (_size > 0) { //line: 1
   77: int _index = 0; //line: 1
   78: for(java.lang.Object _ : __v0) { //line: 1
   79: if (_index++ > 0) {p(",");} //line: 1
   80: boolean _isOdd = _index % 2 == 1; //line: 1



Running org.rythmengine.essential.I18nTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.197 sec
Running org.rythmengine.essential.IfParserTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.565 sec
Running org.rythmengine.essential.ImportParserTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.132 sec
Running org.rythmengine.essential.IncludeParserTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.113 sec
Running org.rythmengine.essential.NoCompactParserTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 sec
Running org.rythmengine.essential.RawParserTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec
Running org.rythmengine.essential.ReturnParserTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.065 sec
Running org.rythmengine.essential.UtilsTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 sec
Running org.rythmengine.essential.VerbatimParserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.04 sec
Running org.rythmengine.issue.GHIssueTest
Tests run: 40, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 1.063 sec
Running org.rythmengine.layout.LayoutTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.355 sec
Running org.rythmengine.render_mode.sandbox.SandboxTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.151 sec
Running org.rythmengine.render_mode.substitute.SubstituteTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec
Running org.rythmengine.render_mode.to_string.ToStringTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.2 sec
Running org.rythmengine.tag.InlineTagTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.128 sec
Running org.rythmengine.tag.InvokeParserTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.171 sec
Running org.rythmengine.tag.InvokeTemplateTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.435 sec
Running org.rythmengine.tag.MacroTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.071 sec
Running org.rythmengine.tag.tagPriorityTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.12 sec

Results :

Tests in error:
  testBasicDirectives(org.rythmengine.advanced.NaturalTemplateTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testFeatureDisabled(org.rythmengine.advanced.NaturalTemplateTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testRangeExpression(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testSimpleStyle(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testLoopVarSize(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testLoopVarParity(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testLoopVarFirstLast(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testBreak(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testBreakWithIf(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testContinue(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testContinueWithIf(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)
  testJoin(org.rythmengine.essential.ForParserTest): The method valueOf(Range) is ambiguous for the type TemplateBase.__Itr(..)

Tests run: 237, Failures: 0, Errors: 12, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.735 s
[INFO] Finished at: 2015-04-04T11:39:22+08:00
[INFO] Final Memory: 29M/349M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project rythm-engine: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/twer/workspace/Rythm/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
➜  Rythm git:(master)
```

**Comment by greenlaw110** [comment]
Yep, I can reproduce it now. Previously forgot a symbol link of jdk dir is still point to the jdk 1.7. Now these issues with JDK 8 is fixed!

**Comment by freewind** [comment]
Yes, I just tried it again, it's successful now. Congratulations!
