### ISSUE TITLE
StringIndexOutOfBoundsException in TemplateBase

### ISSUE THREAD

**Issue by WolfgangFahl** [greenlaw110/Rythm#251]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at org.rythmengine.template.TemplateBase.handleThrowable(TemplateBase.java:711)
	at org.rythmengine.template.TemplateBase.__internalBuild(TemplateBase.java:765)
	at org.rythmengine.template.TemplateBase.__internalRender(TemplateBase.java:785)
	at org.rythmengine.template.TemplateBase.render(TemplateBase.java:602)
	at org.rythmengine.RythmEngine.render(RythmEngine.java:1022)
	at org.rythmengine.Rythm.render(Rythm.java:265)

**Comment by WolfgangFahl** [comment]
>-1 and then substracting 1 won't work.

**Comment by greenlaw110** [comment]
Yes. Can you send me a pull request with the patch? thx!

**Comment by WolfgangFahl** [comment]
Certainly - it's just one line.
https://github.com/greenlaw110/Rythm/pull/258

Am 30.03.15 um 04:58 schrieb Green Luo:
>
> Yes. Can you send me a pull request with the patch? thx!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greenlaw110/Rythm/issues/251#issuecomment-87524089>.
>

-- 

BITPlan - smart solutions
Wolfgang Fahl
Pater-Delp-Str. 1, D-47877 Willich Schiefbahn
Tel. +49 2154 811-480, Fax +49 2154 811-481
Web: http://www.bitplan.de
BITPlan GmbH, Willich - HRB 6820 Krefeld, Steuer-Nr.: 10258040548, Geschäftsführer: Wolfgang Fahl
