### ISSUE TITLE
error in tomcat

### ISSUE THREAD

**Issue by forchr** [greenlaw110/Rythm#265]
23-Apr-2015 09:38:36.522 INFO [Thread-23] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.rythmengine.Rythm$RenderTime]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.rythmengine.Rythm$RenderTime]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1313)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at org.rythmengine.RythmEngine.shutdown(RythmEngine.java:2078)
	at org.rythmengine.RythmEngine$2.run(RythmEngine.java:693)
	at org.rythmengine.DefaultShutdownService$1.run(DefaultShutdownService.java:34)

**Comment by greenlaw110** [comment]
@forchr can you provide the reproduce steps?
