### ISSUE TITLE
Illegal type in constant pool

### ISSUE THREAD

**Issue by 0x6e6562** [greenlaw110/Rythm#274]
We're experiencing the following issue once after each reboot of of our application (i.e. invoking the template a 2nd time doesn't reproduce the issue:

```
Jun 15 14:31:00:  2015-06-15 14:30:59,936 [qtp12209492-23] ERROR s.q.m.r.s.RestResponseEntityExceptionHandler [1000000000000000001:-101] - (class: ASMAccessorImpl_10673308271434378659880, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool 
Jun 15 14:31:00:  Template: fifo.xml 
Jun 15 14:31:00:  Relevant template source lines: 
Jun 15 14:31:00:  ------------------------------------------------- 
Jun 15 14:31:00:     9:       <fifos> 
Jun 15 14:31:00:     10:         @for (FifoGroup g : groups) { 
Jun 15 14:31:00:     11:         <fifo name="@g.getName()" importance="0"> 
Jun 15 14:31:00:     12:           @for (String member : g.getMembers()) { 
Jun 15 14:31:00:  >> 13:           g.getName
Jun 15 14:31:00:     14:           } 
Jun 15 14:31:00:     15:         </fifo> 
Jun 15 14:31:00:     16:         } 
Jun 15 14:31:00:     17:       </fifos> 
Jun 15 14:31:00:  Relevant Java source lines: 
Jun 15 14:31:00:  ------------------------------------------------- 
un 15 14:31:00:     167: try{pe(g.getName());} catch (RuntimeException e) {__handleTemplateExecutionException(e);}  //line: 13 
Jun 15 14:31:00:  >> 170: try{pe((__eval("g.getName()")));} catch (RuntimeException e) {__handleTemplateExecutionException(e);}  //line: 13 
Jun 15 14:31:00:  java.lang.VerifyError: (class: ASMAccessorImpl_10673308271434378659880, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool 
Jun 15 14:31:00:  	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:1.8.0_40] 
Jun 15 14:31:00:  	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[na:1.8.0_40] 
Jun 15 14:31:00:  	at java.lang.Class.getConstructor0(Class.java:3075) ~[na:1.8.0_40] 
Jun 15 14:31:00:  	at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_40] 
Jun 15 14:31:00:  	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:725) ~[mvel2-2.1.5.Final.jar:na] 
Jun 15 14:31:00:  	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:859) ~[mvel2-2.1.5.Final.jar:na] 
Jun 15 14:31:00:  	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor(ASMAccessorOptimizer.java:243) ~[mvel2-2.1.5.Final.jar:na] 
Jun 15 14:31:00:  	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:90) ~[mvel2-2.1.5.Final.jar:na] 
Jun 15 14:31:00:  	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:64) ~[mvel2-2.1.5.Final.jar:na] 
Jun 15 14:31:00:  	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108) ~[mvel2-2.1.5.Final.jar:na] 
```

For reference, this is the environment:

```
$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
$ uname -a
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
```

Has anybody come across this type of issue before?

**Comment by greenlaw110** [comment]
This line looks interesting to me:

```
Jun 15 14:31:00:  >> 13:           g.getName
```

Shouldn't `g.getName` be `@g.getName()`?

**Comment by 0x6e6562** [comment]
I'm sorry but I trimmed out some implementation detail of the XML template to focus on the Rythm issue, and in doing so, I posted something that looks like a bug in the template. However, in the production code it is `@g.getName()`, as you suggest. For me the strange thing is that the only way to reproduce this issue is to start the JVM. After the first invocation, the template executes just fine.

**Comment by greenlaw110** [comment]
Well you need to put the exact information otherwise the solution might be misleading. Specifically to your symptom it looks like raised from the MVEL, which will only be used in evaluation un-typed expression. That says if you are using `@g.name@` rythm will engage `MVEL` to evaluate it, while if you are using `@g.getName()` then rythm will directly get the result of the method call

**Comment by 0x6e6562** [comment]
I totally get where you're coming from - it's hard to debug something when bits of the full story are cut out. Unfortunately, the exact template content contains a bunch of sensitive (and convoluted) information that I can't post on GitHub, so I think the best thing for me to do is to try to come up with a simplified version of the code that reproduces the symptom with all of the noise cut out of it. After I've done that, I can share the results.

**Comment by greenlaw110** [comment]
That would be good. BTW, an open issue with exact the same symptom is logged in MVEL project: https://github.com/mikebrock/mvel/issues/27

**Comment by soojungha** [comment]
I'm having the same issue when upgrading to Java 8.
This issue is apparently fixed in mvel version 2.2.0.Final.
http://markmail.org/message/4qab4chmvhptolqj#query:+page:1+mid:3jvicnq4orfbtasz+state:results
Can you upgrade dependency to mvel?

**Comment by greenlaw110** [comment]
updated. Checkout the latest 1.1.4-SNAPSHOT version

**Comment by soojungha** [comment]
Thanks! Any chance you could release a non snapshot version to maven?

**Comment by greenlaw110** [comment]
@soojungha v1.1.5 has been released in maven repository. Please help to verify if this issue has been fixed on v1.1.5 or not

**Comment by jaapgeurts** [comment]
I have this bug too. For me it often appears after the server has been idle and then busy.
Just wanted to let you know that the pom.xml for the rythm 1.1.5 version on maven central still references the old 2.1.5-Final.

**Comment by greenlaw110** [comment]
Hey thanks for reporting. I've pushed 1.1.6-SNAPSHOT version, please give it a try. If no issue reported I will release 1.1.6 to central repository

**Comment by jaapgeurts** [comment]
The correct jar is now included and initial test runs shows everything is running well. This issue appears intermittently for me. If I get this exception again then I'll let you know. Thanks!

**Comment by rajmalarapu** [comment]
Code within _org.mvel2.optimizers.impl.asm.**ASMAccessorOptimizer**_ should be fixed as shown in below article:
http://copyrightdev.tumblr.com/post/146315831773/getting-drools-5x-to-operate-smoothly-with-java-8

**Comment by advait8** [comment]
hey can you look at my PR: https://github.com/rythmengine/rythmengine/pull/393 . Need to bump up MVEL again so as to support JDK 9,10, 11. Thanks.

**Comment by greenlaw110** [comment]
Hey thanks for the PR. I will take a look over the weekend and get back to
you.

**Comment by advait8** [comment]
hey thanks for merging my PR. Can you also release to maven? Thanks

**Comment by greenlaw110** [comment]
Released to version 1.4.0
