### ISSUE TITLE
Not working deployed GAE server, works on local GAE server.

### ISSUE THREAD

**Issue by valerijus222** [greenlaw110/Rythm#275]
Hey. I configured Rythm to:

RythmEngine engine = null;
Map<String, Object> conf = new HashMap<String, Object>();
conf.put("engine.file_write", false);
engine = new RythmEngine(conf);
String body = engine.render("hello @who!", "kitty");
resp.getWriter().println("{ \"name\": \""+body+"\" }");

Works great on the local GAE server, but the i deploy it on the google server, i get the file write error.
I assume the configuration "engine.file_write" is not changed to false or changed to default.
Why is this happening? Is there a solution?

**Comment by greenlaw110** [comment]
Please attach the error stack from GAE here. thx!

**Comment by valerijus222** [comment]
W 16:39:37.075 org.rythmengine.RythmEngine: Rythm engine : GAE in cloud enabled
    W 16:39:37.102 /demo
      java.lang.RuntimeException: java.lang.NullPointerException
      	at org.rythmengine.internal.compiler.TemplateClassCache.loadTemplateClass(TemplateClassCache.java:148)
      	at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:569)
      	at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:452)
      	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:344)
      	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:327)
      	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:319)
      	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:924)
      	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:947)
      	at org.rythmengine.RythmEngine.render(RythmEngine.java:1021)
      	at org.rythmengine.Rythm.render(Rythm.java:279)
      	at myapp.DemoServlet.doGet(DemoServlet.java:57)
      	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
      	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
      	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
      	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
      	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
      	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
      	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
      	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
      	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
      	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
      	at org.mortbay.jetty.Server.handle(Server.java:326)
      	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
      	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
      	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
      	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
      	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
      	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:527)
      	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
      	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
      	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
      	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
      	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
      	at java.lang.Thread.run(Thread.java:745)
      Caused by: java.lang.NullPointerException
      	at java.io.File.<init>(File.java:450)
      	at org.rythmengine.internal.compiler.TemplateClassCache.getCacheFile(TemplateClassCache.java:247)
      	at org.rythmengine.internal.compiler.TemplateClassCache.getCacheFile(TemplateClassCache.java:260)
      	at org.rythmengine.internal.compiler.TemplateClassCache.loadTemplateClass(TemplateClassCache.java:87)
      	... 44 more
    F 16:39:37.179 Uncaught exception from servlet
      java.lang.RuntimeException: java.lang.NullPointerException
      	at org.rythmengine.internal.compiler.TemplateClassCache.loadTemplateClass(TemplateClassCache.java:148)
      	at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:569)
      	at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:452)
      	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:344)
      	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:327)
      	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:319)
      	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:924)
      	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:947)
      	at org.rythmengine.RythmEngine.render(RythmEngine.java:1021)
      	at org.rythmengine.Rythm.render(Rythm.java:279)
      	at myapp.DemoServlet.doGet(DemoServlet.java:57)
      	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
      	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
      	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
      	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
      	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
      	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
      	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
      	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
      	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
      	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
      	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
      	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
      	at org.mortbay.jetty.Server.handle(Server.java:326)
      	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
      	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
      	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
      	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
      	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
      	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:527)
      	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
      	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
      	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
      	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
      	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
      	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
      	at java.lang.Thread.run(Thread.java:745)
      Caused by: java.lang.NullPointerException
      	at java.io.File.<init>(File.java:450)
      	at org.rythmengine.internal.compiler.TemplateClassCache.getCacheFile(TemplateClassCache.java:247)
      	at org.rythmengine.internal.compiler.TemplateClassCache.getCacheFile(TemplateClassCache.java:260)
      	at org.rythmengine.internal.compiler.TemplateClassCache.loadTemplateClass(TemplateClassCache.java:87)
      	... 44 more
