### ISSUE TITLE
null pointer exception at org.rythmengine.internal.TemplateParser.getRemain()

### ISSUE THREAD

**Issue by WolfgangFahl** [greenlaw110/Rythm#289]
```null
java.lang.NullPointerException
at org.rythmengine.internal.TemplateParser.getRemain(TemplateParser.java:152)
at org.rythmengine.internal.dialect.DialectManager.beginParse(DialectManager.java:98)
at org.rythmengine.internal.TemplateParser.parse(TemplateParser.java:106)
at org.rythmengine.internal.CodeBuilder.build(CodeBuilder.java:848)
at org.rythmengine.internal.compiler.TemplateClass.buildSourceCode(TemplateClass.java:480)
at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:636)
at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:453)
at org.rythmengine.internal.compiler.TemplateClass.(TemplateClass.java:336)
at org.rythmengine.internal.compiler.TemplateClass.(TemplateClass.java:324)
at com.bitplan.rythm.WikiTemplateResourceLoader.registerTemplate(WikiTemplateResourceLoader.java:173)
at com.bitplan.rythm.WikiTemplateResourceLoader.tryLoadTemplate(WikiTemplateResourceLoader.java:200)
at org.rythmengine.resource.TemplateResourceManager.tryLoadTemplate(TemplateResourceManager.java:223)
at org.rythmengine.RythmEngine.testTemplate(RythmEngine.java:1621)
at org.rythmengine.internal.CodeBuilder.addInclude(CodeBuilder.java:557)
at org.rythmengine.internal.CodeBuilder.addIncludes(CodeBuilder.java:544)
at org.rythmengine.internal.parser.build_in.IncludeParser$1.go(IncludeParser.java:76)
at org.rythmengine.internal.parser.ParserDispatcher.go2(ParserDispatcher.java:57)
at org.rythmengine.internal.TemplateTokenizer$2.next(TemplateTokenizer.java:88)
at org.rythmengine.internal.TemplateTokenizer$2.next(TemplateTokenizer.java:1)
at org.rythmengine.internal.TemplateParser.parse(TemplateParser.java:110)
at org.rythmengine.internal.CodeBuilder.build(CodeBuilder.java:848)
at org.rythmengine.internal.compiler.TemplateClass.buildSourceCode(TemplateClass.java:480)
at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:636)
at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:453)
at org.rythmengine.internal.compiler.TemplateClass.(TemplateClass.java:345)
at org.rythmengine.internal.compiler.TemplateClass.(TemplateClass.java:328)
at org.rythmengine.internal.compiler.TemplateClass.(TemplateClass.java:320)
at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:924)
at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:947)
at org.rythmengine.RythmEngine.render(RythmEngine.java:1021)```

you might want not to assume that the template is non null here.

**Comment by WolfgangFahl** [comment]
after fixing this with
```
 @Override
    public String getRemain() {
      String result="";
      if (template!=null) {
        result=cursor < template.length() ? template.substring(cursor) : "";  
      }
      return result;
    }
```
another null pointer exception pops up in hasremain which i'm trying to fix with
``` @Override
    public boolean hasRemain() {
        return template!=null && cursor < template.length();
    }
```
